# Top-level configuration
name = "asteroidv3"
main = "src/index.js"
compatibility_date = "2024-09-27"

workers_dev = false
[site]
bucket = "./static
pages_build_output_dir = '/src/static'
[build]

command = "npm install @titaniumnetwork-dev/ultraviolet"
command = "npm install express"
command = "npm install socks-proxy-agent"
command = "npm install dotenv"
command = "npm install url"
command = "npm install"
command = "npm start"
command = "npm install @tomphttp/bare-server-node"
