# Top-level configuration
name = "asteroidv3"
main = "src/index.js"
compatibility_date = "2024-09-27"

workers_dev = false


[build]
command = "npm install --global @tomphttp/bare-server-node"
command = "npm install @titaniumnetwork-dev/ultraviolet"
command = "npm install express"
command = "npm install socks-proxy-agent"
command = "npm install dotenv"
command = "npm install url"
command = "npm install"
command = "npm start"
pages_build_output_dir = '/src/static'

cwd = "build_cwd"
watch_dir = "build_watch_dir"
