# Top-level configuration
name = "asteroidv3"
main = "src/index.js"
compatibility_date = "2024-09-27"

workers_dev = false
[site]
bucket = "./static
pages_build_output_dir = '/src/static'

[build]
cwd = "build_cwd"
watch_dir = "build_watch_dir"
command = "npm install @tomphttp/bare-server-node && npm install @titaniumnetwork-dev/ultraviolet && npm install express && npm install socks-proxy-agent && npm install dotenv && npm install url && npm install && npm start"
